Name=input("enter emp name: ")
empid=int(input("enter emp id:"))
empdesig=input("enter designstion:")
empdoj=input("enter doj mm/dd/yyyy: ")
empsal=float(input("enter the salary:"))

print("#"*40)
print("employe profile")
print("#"*40)
print("Employee name",Name)
print("Employee id",empid)
print("Employee designstion",empdesig)
print("Employee date os joining",empdoj)
print("Employee salary",empsal)